export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGING_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";

export const IS_AUTH = "IS_AUTH";

//user Profile
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const GET_LOGGED_IN = "GET_LOGGED_IN";
export const REQUEST_LOGGED_IN_SUCCESS = "REQUEST_LOGGED_IN_SUCCESS";
export const REQUEST_LOGGED_IN_FAILED = "REQUEST_LOGGED_IN_FAILED";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const GET_POSTS_LOADING = "POSTS_LOADING";
export const GET_POSTS_SUCCESS = "POSTS_SUCCESS";
export const ADD_POST = "ADD_POST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const ADD_LIKE = "ADD_LIKE";
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const REMOVE_LIKE = "REMOVE_LIKE";
export const REMOVE_LIKE_SUCCESS = "REMOVE_LIKE_SUCCESS";
export const UPDATE_LIKES_SOCKET = "POST_SOCKET";
export const UPDATE_COMMENTS_SOCKET = "POST_COMMENTS";

export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

export const ADD_DELETE_FOLLOW = "ADD_DELETE_FOLLOW";
export const ADD_FOLLOW = "ADD_FOLLOW";
export const DELETE_FOLLOW = "DELETE_FOLLOW";

export const CLOSE_MSG_ERROR = "SHOW_MSG_ERROR";
// chat
export const GET_ALL_CONVERSATIONS = "GET_ALL_CONVERSATIONS";
export const GET_ALL_CONVERSATIONS_SUCCESS = "GET_ALL_CONVERSATIONS_SUCCESS";
export const GET_ALL_CONVERSATIONS_FAILED = "GET_ALL_CONVERSATIONS_FAILED";
export const ADD_DELETE_POST = "ADD_DELETE_POST";

export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAILED = "GET_ALL_MESSAGES_FAILED";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";
export const UPDATE_MSGS = "UPDATE_MSGS";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_LOGIN = "SET_LOGIN";
